BTStoreWebUI/Areas/Admin/Controllers/BrandsController.cs
using BTStore.Entity.Entities.Concrete;
using BTStore.Service.Interfaces;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using Microsoft.Extensions.Hosting;
using System.Drawing.Drawing2D;
using System.Reflection.Metadata;

namespace BTStoreWebUI.Areas.Admin.Controllers
{
    [Area("Admin")]
    public class BrandsController : Controller
    {
        private readonly IService<Brand> _brandService;
        private readonly IWebHostEnvironment _webHostEnvironment;

        public BrandsController(IService<Brand> brandService, IWebHostEnvironment webHostEnvironment)
        {
            _brandService = brandService;
            _webHostEnvironment = webHostEnvironment;
        }

        public async Task<IActionResult> BrandList()
        {
            var model = await _brandService.GetAllAsync();

            return View(model);
        }

        [HttpGet]
        public IActionResult BrandCreate()
        {
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> BrandCreate(Brand brand)
        {
            if (ModelState.IsValid)
            {
               // await ImageUpload();

                try
                {
                    ImageUpload(brand);

                    await _brandService.AddAsync(brand);

                    await _brandService.SaveChangesAsync();

                    return RedirectToAction(nameof(BrandList));
                }
                catch
                {

                    ModelState.AddModelError("", "Hata Oluştu!!");
                }
            }

            return View(brand);
        }

        [HttpGet]
        public async Task<IActionResult> BrandEdit(int id)
        {
            var model = await _brandService.FindAsync(id);

            return View(model);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> BrandEdit(int id, Brand brand)
        {
            if (ModelState.IsValid)
            {
                 
                try
                {
                    ImageUpload(brand);

                    _brandService.Update(brand);

                    await _brandService.SaveChangesAsync();

                    return RedirectToAction(nameof(BrandList));
                }
                catch
                {
                    ModelState.AddModelError("", "Hata Oluştu!!");
                }
            }

            return View(brand);
        }

        [HttpGet]
        public async Task<IActionResult> BrandDelete(int id)
        {
            var model = await _brandService.FindAsync(id);

            return View(model);
        }

        [HttpPost]
        public async Task<IActionResult> BrandDelete(int id, Brand brand)
        {
            try
            {
                //brand = await _brandService.FindAsync(id);

                //var imagePath = Path.Combine(_webHostEnvironment.WebRootPath, brand.Image.TrimStart('\\'));

                ////menü silindiğinde menü resmininde silinmesini sağlar
                //if (System.IO.File.Exists(imagePath))
                //{
                //    System.IO.File.Delete(imagePath);
                //}

                _brandService.Delete(brand);

                

                await _brandService.SaveChangesAsync();

                return RedirectToAction(nameof(BrandList));
            }
            catch
            {
                return View();
            }
        }

        /// <summary>
        /// veritabanına resim ekler
        /// </summary>
        /// <returns></returns>
        private void ImageUpload(Brand brand)
        {
            var files = HttpContext.Request.Form.Files;

            if (files.Count > 0)
            {
                var fileName = Guid.NewGuid().ToString();
                //Site/menu adındaki yere resmi ekler
                var uploads = Path.Combine(_webHostEnvironment.WebRootPath, @"images\brands");

                var ext = Path.GetExtension(files[0].FileName);

                //resim alanı boş değilse resimleri ekler
                if (brand.Image != null)
                {
                    var imagePath = Path.Combine(_webHostEnvironment.WebRootPath, brand.Image.TrimStart('\\'));

                    //menü silindiğinde menü resmininde silinmesini sağlar
                    if (System.IO.File.Exists(imagePath))
                    {
                        System.IO.File.Delete(imagePath);
                    }
                }

                using (var filesStreams = new FileStream(Path.Combine(uploads, fileName + ext), FileMode.Create))
                {
                    files[0].CopyTo(filesStreams);
                }

                brand.Image = @"\images\brands\" + fileName + ext;
            }
        }

        /// <summary>
        /// resmi veritabanından siler
        /// </summary>
        /// <param name="id"></param>
        /// <param name="brand"></param>
        /// <returns></returns>
        private void ImageDeleteToDatabase()
        {
            Brand brand = new Brand();

            brand =  _brandService.Find(brand.Id);
            var imagePath = Path.Combine(_webHostEnvironment.WebRootPath, brand.Image.TrimStart('\\'));

            //menü silindiğinde menü resmininde silinmesini sağlar
            if (System.IO.File.Exists(imagePath))
            {
                System.IO.File.Delete(imagePath);
            }
        }
    }
}

BTStoreWebUI/Areas/Admin/Views/Brands/BrandCreate.cshtml
@model Brand
@{
    ViewData["Title"] = "Marka Ekle";
    Layout = "~/Areas/Admin/Views/Shared/_AdminLayout.cshtml";
}

<h1 class="text-center text-success">@ViewData["Title"]</h1>

<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="BrandCreate" enctype="multipart/form-data">

            <div asp-validation-summary="ModelOnly" class="text-danger"></div>

            <div class="form-group">
                <label asp-for="Name" class="control-label"></label>
                <input asp-for="Name" class="form-control" />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>

            <br />

            <div class="form-group">
                <label asp-for="Image" class="control-label"></label>
                <input asp-for="Image" class="form-control" type="file" />
                <span asp-validation-for="Image" class="text-danger"></span>
            </div>

            <br />

            <div class="form-group form-check">
                <label class="form-check-label">
                    <input class="form-check-input" asp-for="IsActive" /> @Html.DisplayNameFor(model => model.IsActive)
                </label>
            </div>

            <div class="form-group">
                <label asp-for="Description" class="control-label"></label>
                <textarea asp-for="Description" class="form-control" rows="10" placeholder="açıklama yazısı giriniz"></textarea>
                <span asp-validation-for="Description" class="text-danger"></span>
            </div>
            
            <br />

            <div class="form-group">
                <input type="submit" value="Ekle" class="btn btn-outline-primary" />
                <a asp-area="Admin" asp-controller="Brands" asp-action="BrandList" class="btn btn-outline-danger">İptal</a>
            </div>
        </form>
    </div>
</div>

BTStoreWebUI/Areas/Admin/Views/Brands/BrandDelete.cshtml
@model Brand
@{
    ViewData["Title"] = "BrandDelete";
    Layout = "~/Areas/Admin/Views/Shared/_AdminLayout.cshtml";
}

<h1 class="text-center text-success">@ViewData["Title"]</h1>

<br />

<div class="row text-center">
    <p>
        <b class="text-success">@Model.Name</b> adlı veriyi silmek istiyor musunuz?
    </p>
</div>


<div class="row text-center">
    @using (Html.BeginForm())
    {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Sil" class="btn btn-outline-warning" />
            <a asp-area="Admin" asp-controller="Brands" asp-action="BrandList" class="btn btn-outline-danger">İptal</a>
        </div>
    }
</div>

BTStoreWebUI/Areas/Admin/Views/Brands/BrandEdit.cshtml
@model Brand
@{
    ViewData["Title"] = "Marka Düzenle";
    Layout = "~/Areas/Admin/Views/Shared/_AdminLayout.cshtml";
}



<h1 class="text-center text-success">@ViewData["Title"]</h1>

<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="BrandEdit" enctype="multipart/form-data">

            <div asp-validation-summary="ModelOnly" class="text-danger"></div>

            <input type="hidden" asp-for="Id" />
            <input type="hidden" asp-for="Image" />
            <input type="hidden" asp-for="CreateDate" />

            <div class="form-group">
                <label asp-for="Name" class="control-label"></label>
                <input asp-for="Name" class="form-control" />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>

            <br />

            <div class="form-group">
                <label class="control-label">Eski Resim</label>
                <br />
                <img src="@Model.Image" height="30" />
            </div>

            <br />

            <div class="form-group">
                <label asp-for="Image" class="control-label"></label>
                <input asp-for="Image" class="form-control" type="file" />
                <span asp-validation-for="Image" class="text-danger"></span>
            </div>

            <br />

            <div class="form-group form-check">
                <label class="form-check-label">
                    <input class="form-check-input" asp-for="IsActive" /> @Html.DisplayNameFor(model => model.IsActive)
                </label>
            </div>

            <div class="form-group">
                <label asp-for="Description" class="control-label"></label>
                <textarea asp-for="Description" class="form-control" rows="10" placeholder="açıklama yazısı giriniz"></textarea>
                <span asp-validation-for="Description" class="text-danger"></span>
            </div>

            <br />

            <div class="form-group">
                <input type="submit" value="Güncelle" class="btn btn-outline-info" />
                <a asp-area="Admin" asp-controller="Brands" asp-action="BrandList" class="btn btn-outline-danger">İptal</a>
            </div>
        </form>
    </div>
</div>

BTStoreWebUI/Areas/Admin/Views/Brands/BrandList.cshtml
@model IEnumerable<Brand>
@{
    ViewData["Title"] = "Markalar Listesi";
    Layout = "~/Areas/Admin/Views/Shared/_AdminLayout.cshtml";
}

<h1 class="text-center text-success">@ViewData["Title"]</h1>

<p>
    <a asp-area="Admin" asp-controller="Brands" asp-action="BrandCreate" class="btn btn-outline-primary btn-sm">Yeni Ekle</a>
</p>

<table class="table table-striped table-hover">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.Name)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Image)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.IsActive)
        </th>
        <th></th>
    </tr>

    @foreach (var item in Model)
    {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Name)
            </td>
            <td>
                @if (item.Image == null)
                {
                    <img src="~/images/noImage.png" width="25" height="25">
                }
                else
                {
                    <img src="@item.Image" width="25" height="25">
                }
            </td>
            <td>
                <img src="~/images/brands/@item.Id" />
                @Html.DisplayFor(modelItem => item.IsActive)
            </td>
            <td>
                <a asp-area="Admin" asp-controller="Brands" asp-action="BrandEdit" asp-route-id="@item.Id" class="btn btn-outline-info btn-sm">Düzenle</a>
                <a asp-area="Admin" asp-controller="Brands" asp-action="BrandDelete" asp-route-id="@item.Id" class="btn btn-outline-danger btn-sm">Sil</a>
            </td>
        </tr>
    }

</table>