BTStoreWebUI/Areas/Admin/Controllers/AppUsersController.cs
using BTStore.Entity.Entities.Concrete;
using BTStore.Service.Interfaces;
using BTStore.Service.Repositories;
using Microsoft.AspNetCore.Mvc;

namespace BTStoreWebUI.Areas.Admin.Controllers
{
    [Area("Admin")]
    public class AppUsersController : Controller
    {
        private readonly IService<AppUser> _service;

        public AppUsersController(IService<AppUser> service)
        {
            _service = service;
        }

        public async Task<IActionResult> UserList()
        {
            var model =await _service.GetAllAsync();

            return View(model);
        }

        public IActionResult Details()
        {
            return View();
        }

        [HttpGet]
        public async Task<IActionResult> UserCreate()
        {
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> UserCreate(AppUser appuser)
        {
            try
            {
                await _service.AddAsync(appuser);

                await _service.SaveChangesAsync();

                return RedirectToAction(nameof(UserList));
            }
            catch
            {

                ModelState.AddModelError("", "hata oluştu!!");
            }

            return View(appuser);
        }

        [HttpGet]
        public async Task<IActionResult> UserEdit(int id)
        {
            var model = await _service.FindAsync(id);

            return View(model);
        }

        [HttpPost]
        public async Task<IActionResult> UserEdit(int id, AppUser appUser)
        {
            try
            {
                _service.Update(appUser);

                await _service.SaveChangesAsync();

                return RedirectToAction(nameof(UserList));
            }
            catch
            {

                return View();
            }

        }

        [HttpGet]
        public async Task<IActionResult> UserDelete(int id)
        {
            var model = await _service.FindAsync(id);

            return View(model);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> UserDelete(int id, AppUser appUser)
        {
            try
            {
                var model = await _service.FindAsync(id);
                _service.Delete(model);

                await _service.SaveChangesAsync();

                return RedirectToAction(nameof(UserList));
            }
            catch
            {

                return View();
            }
        }
    }
}

BTStoreWebUI/Areas/Admin/Views/AppUsers/Details.cshtml
@{
    ViewData["Title"] = "Details";
    Layout = "~/Areas/Admin/Views/Shared/_AdminLayout.cshtml";
}

<h1>Details</h1>

BTStoreWebUI/Areas/Admin/Views/AppUsers/UserCreate.cshtml
@model AppUser
@{
    ViewData["Title"] = "Kullanıcı Ekle";
    Layout = "~/Areas/Admin/Views/Shared/_AdminLayout.cshtml";
}

<h1 class="text-center text-success">@ViewData["Title"]</h1>

<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="UserCreate" method="post">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>


            <div class="form-group">
                <label asp-for="Name" class="control-label col-md-2"></label>
                <div class="col-md-10">
                    <input asp-for="Name" class="form-control" />
                    <span asp-validation-for="Name" class="text-danger"></span>
                </div>
            </div>

            <div class="form-group">
                <label asp-for="Surname" class="control-label"></label>
                <input asp-for="Surname" class="form-control" />
                <span asp-validation-for="Surname" class="text-danger"></span>
            </div>

            <div class="form-group">
                <label asp-for="Username" class="control-label"></label>
                <input asp-for="Username" class="form-control" />
                <span asp-validation-for="Username" class="text-danger"></span>
            </div>

            <div class="form-group">
                <label asp-for="Email" class="control-label"></label>
                <input asp-for="Email" class="form-control" />
                <span asp-validation-for="Email" class="text-danger"></span>
            </div>

            <div class="form-group">
                <label asp-for="Phone" class="control-label"></label>
                <input asp-for="Phone" class="form-control" />
                <span asp-validation-for="Phone" class="text-danger"></span>
            </div>

            <div class="form-group">
                <label asp-for="Password" class="control-label"></label>
                <input asp-for="Password" class="form-control" />
                <span asp-validation-for="Password" class="text-danger"></span>
            </div>

            <div class="form-group form-check">
                <label class="form-check-label">
                    <input class="form-check-input" asp-for="IsActive" /> @Html.DisplayNameFor(model => model.IsActive)
                </label>
            </div>

            <div class="form-group form-check">
                <label class="form-check-label">
                    <input class="form-check-input" asp-for="IsAdmin" /> @Html.DisplayNameFor(model => model.IsAdmin)
                </label>
            </div>

            <div class="form-group">
                <input type="submit" value="Ekle" class="btn btn-primary btn-sm" />
                <a asp-area="Admin" asp-controller="AppUsers" asp-action="UserList" class="btn btn-outline-danger btn-sm">İptal</a>
            </div>
        </form>
    </div>
</div>

BTStoreWebUI/Areas/Admin/Views/AppUsers/UserDelete.cshtml
@model AppUser
@{
    ViewData["Title"] = "Kullanıcı Sil";
    Layout = "~/Areas/Admin/Views/Shared/_AdminLayout.cshtml";
}

<h1 class="text-center text-success">@ViewData["Title"]</h1>

<br />

<div class="row text-center">
    <p>
        <b class="text-success">@Model.Name @Model.Surname</b> adlı kullanıcıyı silmek istiyor musunuz?
    </p>
</div>


<div class="row text-center">
    @using (Html.BeginForm())
    {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Sil" class="btn btn-outline-warning" /> 
            <a asp-area="Admin" asp-controller="AppUsers" asp-action="UserList" class="btn btn-outline-danger">İptal</a>
        </div>
    }
</div>

BTStoreWebUI/Areas/Admin/Views/AppUsers/UserEdit.cshtml
@model AppUser
@{
    ViewData["Title"] = "Kullanıcı Düzenle";
    Layout = "~/Areas/Admin/Views/Shared/_AdminLayout.cshtml";
}

<h1 class="text-center text-success">@ViewData["Title"]</h1>

<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="UserEdit" method="post">

            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            
            <input type="hidden" asp-for="Id" />
            
            <div class="form-group">
                <label asp-for="Name" class="control-label col-md-2"></label>
                <div class="col-md-10">
                    <input asp-for="Name" class="form-control" />
                    <span asp-validation-for="Name" class="text-danger"></span>
                </div>
            </div>

            <div class="form-group">
                <label asp-for="Surname" class="control-label"></label>
                <input asp-for="Surname" class="form-control" />
                <span asp-validation-for="Surname" class="text-danger"></span>
            </div>

            <div class="form-group">
                <label asp-for="Username" class="control-label"></label>
                <input asp-for="Username" class="form-control" />
                <span asp-validation-for="Username" class="text-danger"></span>
            </div>

            <div class="form-group">
                <label asp-for="Email" class="control-label"></label>
                <input asp-for="Email" class="form-control" />
                <span asp-validation-for="Email" class="text-danger"></span>
            </div>

            <div class="form-group">
                <label asp-for="Phone" class="control-label"></label>
                <input asp-for="Phone" class="form-control" />
                <span asp-validation-for="Phone" class="text-danger"></span>
            </div>

            <div class="form-group">
                <label asp-for="Password" class="control-label"></label>
                <input asp-for="Password" class="form-control" />
                <span asp-validation-for="Password" class="text-danger"></span>
            </div>

            <div class="form-group form-check">
                <label class="form-check-label">
                    <input class="form-check-input" asp-for="IsActive" /> @Html.DisplayNameFor(model => model.IsActive)
                </label>
            </div>

            <div class="form-group form-check">
                <label class="form-check-label">
                    <input class="form-check-input" asp-for="IsAdmin" /> @Html.DisplayNameFor(model => model.IsAdmin)
                </label>
            </div>

            <div class="form-group">
                <input type="submit" value="Güncelle" class="btn btn-outline-info" />
                <a asp-area="Admin" asp-controller="AppUsers" asp-action="UserList" class="btn btn-outline-danger">Listeye Dön</a>
            </div>
        </form>
    </div>
</div>

BTStoreWebUI/Areas/Admin/Views/AppUsers/UserList.cshtml
@model IEnumerable<AppUser>
@{
    ViewData["Title"] = "Kullanıcı Listesi";
    Layout = "~/Areas/Admin/Views/Shared/_AdminLayout.cshtml";
}

<h1 class="text-center text-success">@ViewData["Title"]</h1>

<p>
    <a asp-area="Admin" asp-controller="AppUsers" asp-action="UserCreate" class="btn btn-outline-primary btn-sm">Ekle</a>
    
</p>
<table class="table table-striped table-hover">
    <tr>
        <th>
            Ad Soyad
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Email)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Username)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.CreateDate)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.IsActive)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.IsAdmin)
        </th>
        <th></th>
    </tr>

    @foreach (var item in Model)
    {
        <tr>
            <td>
                @item.Name @item.Surname
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Email)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Username)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.CreateDate)
                
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.IsActive)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.IsAdmin)
            </td>
            <td>
                <a asp-area="Admin" asp-controller="AppUsers" asp-action="UserEdit" asp-route-id="@item.Id" class="btn btn-outline-info btn-sm">Düzenle</a>
                <a asp-area="Admin" asp-controller="AppUsers" asp-action="UserDelete" asp-route-id="@item.Id" class="btn btn-outline-danger btn-sm">Sil</a>
                
            </td>
        </tr>
    }

</table>